name: "Open a Github issue Testing Gen"
author: Genaro
description: "Opens a Github issue"
inputs: 
  token:
    description: "Github token"
    required: true
  title: 
    description: "Issue title"
    required: true
  body: 
    description: "Body title"
    required: true
  assignees: 
    description: "Issue Assignees"
    required: true
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
branding: 
  icon: "alert-octagon"
  color: "purple"
